import { Product } from './types/product';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: 'PlayStation 5 Digital',
    slug: 'playstation-5-digital',
    heroImage: require('../assets/images/ps-5-1.jpg'),
    imagesUrl: [
      require('../assets/images/ps-5-1.jpg'),
      require('../assets/images/ps-5-2.jpg'),
      require('../assets/images/ps-5-3.jpg'),
    ],
    price: 499.0,
    category: {
      imageUrl: require('../assets/images/ps-5-1.jpg'),
      name: 'Consoles',
      slug: 'consoles',
    },
    maxQuantity: 2,
    rating: 4.9,
    badge: 'Hot',
    description: 'Ultra-fast SSD, 4K gaming, and haptic feedback in a sleek digital console.',
  },
  {
    id: 2,
    title: 'Xbox Series X',
    slug: 'xbox-series-x',
    heroImage: require('../assets/images/ps-5-2.jpg'),
    imagesUrl: [
      require('../assets/images/ps-5-2.jpg'),
      require('../assets/images/ps-5-1.jpg'),
    ],
    price: 529.0,
    category: {
      imageUrl: require('../assets/images/ps-5-2.jpg'),
      name: 'Consoles',
      slug: 'consoles',
    },
    maxQuantity: 2,
    rating: 4.8,
    badge: 'Pro',
    description: 'Next-gen performance with 4K gaming and lightning-fast load times.',
  },
  {
    id: 3,
    title: 'Nintendo Switch OLED',
    slug: 'nintendo-switch-oled',
    heroImage: require('../assets/images/nintendo-switch-1.jpg'),
    imagesUrl: [
      require('../assets/images/nintendo-switch-1.jpg'),
      require('../assets/images/nintendo-switch-2.jpg'),
    ],
    price: 349.0,
    category: {
      imageUrl: require('../assets/images/nintendo-switch-1.jpg'),
      name: 'Consoles',
      slug: 'consoles',
    },
    maxQuantity: 3,
    rating: 4.7,
    badge: 'New',
    description: 'Brilliant OLED display with vibrant colors for handheld play.',
  },
  {
    id: 4,
    title: 'Apex Gaming PC S',
    slug: 'apex-gaming-pc-s',
    heroImage: require('../assets/images/mac-book-1.jpg'),
    imagesUrl: [
      require('../assets/images/mac-book-1.jpg'),
      require('../assets/images/mac-book-2.jpg'),
    ],
    price: 1599.0,
    category: {
      imageUrl: require('../assets/images/mac-book-1.jpg'),
      name: 'Gaming PCs',
      slug: 'gaming-pcs',
    },
    maxQuantity: 1,
    rating: 4.6,
    badge: 'Build',
    description: 'Smooth 1440p gaming with a clean, compact chassis.',
  },
  {
    id: 5,
    title: 'Nebula Gaming Laptop 15',
    slug: 'nebula-gaming-laptop-15',
    heroImage: require('../assets/images/dell-1.jpg'),
    imagesUrl: [
      require('../assets/images/dell-1.jpg'),
      require('../assets/images/dell-2.jpg'),
    ],
    price: 1299.0,
    category: {
      imageUrl: require('../assets/images/dell-1.jpg'),
      name: 'Laptops',
      slug: 'laptops',
    },
    maxQuantity: 2,
    rating: 4.5,
    badge: 'Fast',
    description: 'Portable power with a high-refresh display and RTX graphics.',
  },
  {
    id: 6,
    title: 'HyperDrive Racing Wheel',
    slug: 'hyperdrive-racing-wheel',
    heroImage: require('../assets/images/head-set-1.jpg'),
    imagesUrl: [
      require('../assets/images/head-set-1.jpg'),
      require('../assets/images/head-set-2.jpg'),
    ],
    price: 219.0,
    category: {
      imageUrl: require('../assets/images/head-set-1.jpg'),
      name: 'Wheels',
      slug: 'wheels',
    },
    maxQuantity: 4,
    rating: 4.3,
    badge: 'Smooth',
    description: 'Force feedback wheel with metal pedals for sim racing.',
  },
  {
    id: 7,
    title: 'Pulse Wireless Headset',
    slug: 'pulse-wireless-headset',
    heroImage: require('../assets/images/head-set-2.jpg'),
    imagesUrl: [
      require('../assets/images/head-set-2.jpg'),
      require('../assets/images/head-set-1.jpg'),
    ],
    price: 129.0,
    category: {
      imageUrl: require('../assets/images/head-set-2.jpg'),
      name: 'Accessories',
      slug: 'accessories',
    },
    maxQuantity: 6,
    rating: 4.4,
    badge: 'Clear',
    description: 'Immersive surround audio with studio-tuned drivers.',
  },
  {
    id: 8,
    title: 'UltraGear 27" Monitor',
    slug: 'ultragear-27-monitor',
    heroImage: require('../assets/images/samsung-1.jpg'),
    imagesUrl: [
      require('../assets/images/samsung-1.jpg'),
      require('../assets/images/samsung-2.jpg'),
    ],
    price: 329.0,
    category: {
      imageUrl: require('../assets/images/samsung-1.jpg'),
      name: 'Monitors',
      slug: 'monitors',
    },
    maxQuantity: 4,
    rating: 4.5,
    badge: '144Hz',
    description: 'Fast response IPS panel with buttery-smooth refresh.',
  },
  {
    id: 9,
    title: 'PSN Gift Card $50',
    slug: 'psn-gift-card-50',
    heroImage: require('../assets/images/i-phone-1.jpg'),
    imagesUrl: [require('../assets/images/i-phone-1.jpg')],
    price: 50.0,
    category: {
      imageUrl: require('../assets/images/i-phone-1.jpg'),
      name: 'Cards',
      slug: 'cards',
    },
    maxQuantity: 10,
    rating: 4.9,
    badge: 'Instant',
    description: 'Top up your PlayStation wallet instantly.',
  },
  {
    id: 10,
    title: 'Xbox Game Pass 3-Mo',
    slug: 'xbox-game-pass-3-mo',
    heroImage: require('../assets/images/i-phone-2.jpg'),
    imagesUrl: [require('../assets/images/i-phone-2.jpg')],
    price: 44.99,
    category: {
      imageUrl: require('../assets/images/i-phone-2.jpg'),
      name: 'Cards',
      slug: 'cards',
    },
    maxQuantity: 10,
    rating: 4.8,
    badge: 'Cloud',
    description: 'Three months of unlimited games on console and PC.',
  },
];
